language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-loaded-edm' ]; then cd .. && eval "mv $currentfolder generator-loaded-edm" && cd generator-loaded-edm; fi

